# Generated by Django 6.0.3 on 2026-06-03 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Chỉ chữ thường, số, dấu - và _. Ví dụ: about-us, home_page', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Chỉ cho phép chữ thường (a-z), số (0-9), dấu gạch ngang (-) và gạch dưới (_).', regex='^[a-z0-9_-]+$')], verbose_name='Mã trang')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(help_text='Nội dung trang, có thể chứa HTML', verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Webpage',
                'verbose_name_plural': 'Webpages',
                'ordering': ['-created_at'],
            },
        ),
    ]
